# Travis CI build file for KituraBuddy.

#language: c

branches:
  only:
    - master
    - develop
    - /^issue.*$/

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.8
#          packages:
#            - clang-3.8
#      env:
#        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"
#        - COMPILER=clang++-3.8
#    - os: osx
#      osx_image: xcode9
#      sudo: required

before_install:
#  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - sudo apt-get update && sudo apt-get install -y clang-3.8 lldb-3.8
  - sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.8 500
  - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.8 500
  - sudo ls -la /usr/bin/clang++
  - sudo ls -la /usr/bin/clang
  - sudo ls -la /etc/alternatives/clang++
  - sudo ls -la /etc/alternatives/clang
  - clang --version
#  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
